<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net8.0-tizen</TargetFrameworks> -->

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>Mediathek</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>Mediathek</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.mediathek</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">16.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">13.1</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)'=='net8.0-ios'">
	  <ProvisioningType>manual</ProvisioningType>
	  <CodesignProvision>VS: WildCard Development</CodesignProvision>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-ios|AnyCPU'">
	  <NoWarn>1701;1702;8602;8603;8600;8622;8618;8601;8604;8625</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-ios|AnyCPU'">
	  <NoWarn>1701;1702;8602;8603;8600;8622;8618;8601;8604;8625</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-maccatalyst|AnyCPU'">
	  <NoWarn>1701;1702;8602;8603;8600;8622;8618;8601;8604;8625</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-maccatalyst|AnyCPU'">
	  <NoWarn>1701;1702;8602;8603;8600;8622;8618;8601;8604;8625</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-windows10.0.19041.0|AnyCPU'">
	  <NoWarn>1701;1702;8602;8603;8600;8622;8618;8601;8604;8625</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-windows10.0.19041.0|AnyCPU'">
	  <NoWarn>1701;1702;8602;8603;8600;8622;8618;8601;8604;8625</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.png">
		  <Color>#CDCDCD</Color>
		  <BaseSize>512,512</BaseSize>
		</MauiIcon>

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />
		<MauiSplashScreen Include="Resources\Splash\videoplayer.png">
		  <Color>#000000</Color>
		  <BaseSize>512,512</BaseSize>
		</MauiSplashScreen>

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Resources\AppIcon\appicon.png" />
	  <None Remove="Resources\Images\add.png" />
	  <None Remove="Resources\Images\add_folder.png" />
	  <None Remove="Resources\Images\back.png" />
	  <None Remove="Resources\Images\cancel.png" />
	  <None Remove="Resources\Images\check.png" />
	  <None Remove="Resources\Images\delete.png" />
	  <None Remove="Resources\Images\download.png" />
	  <None Remove="Resources\Images\fullscreen.png" />
	  <None Remove="Resources\Images\icon_rescan.png" />
	  <None Remove="Resources\Images\left.png" />
	  <None Remove="Resources\Images\next.png" />
	  <None Remove="Resources\Images\pause.png" />
	  <None Remove="Resources\Images\play.png" />
	  <None Remove="Resources\Images\playlist.png" />
	  <None Remove="Resources\Images\previous.png" />
	  <None Remove="Resources\Images\process.png" />
	  <None Remove="Resources\Images\right.png" />
	  <None Remove="Resources\Images\setup.png" />
	  <None Remove="Resources\Images\uncategorized.png" />
	  <None Remove="Resources\Images\window.png" />
	  <None Remove="Resources\Raw\AboutAssets.txt" />
	  <None Remove="Resources\Raw\loading.mp4" />
	  <None Remove="Resources\Raw\secrets.json" />
	  <None Remove="Resources\Splash\videoplayer.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui.MediaElement" Version="3.0.1" />
		<PackageReference Include="Magick.NET-Q16-AnyCPU" Version="13.5.0" />
		<PackageReference Include="Magick.NET.Core" Version="13.5.0" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\MediathekMaui\MediathekMaui.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Platforms\Windows\TouchEffect.cs">
	    <ExcludeFromCurrentConfiguration>false</ExcludeFromCurrentConfiguration>
	  </Compile>
	  <Compile Update="Platforms\Windows\TouchPlatformEffect.cs">
	    <ExcludeFromCurrentConfiguration>false</ExcludeFromCurrentConfiguration>
	  </Compile>
	  <Compile Update="Views\Categorization\MediaItemCardPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\Homepage\CategorySelection.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\Homepage\HomePageView.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\Homepage\HorizontalMediaItemCollection.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\MainPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\ManagementPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\Management\AdministrativeTasks\AdminTasksView.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\Management\SettingsView.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\Management\SourcesView.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\Management\Sources\SourceConfigurationBox.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\Management\Sources\SourceFTPConfigurationBox.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\Management\Sources\SourceHttpConfigurationBox.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\Management\Sources\SourceSSHConfigurationBox.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\MediaLists\Cards\MovieCardPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\MediaLists\Cards\MovieSetupView.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\MediaLists\Cards\TVShowCardPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\MediaLists\Cards\TVShowSetupView.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\MediaLists\ListItems\MediaListItemBoxView.xaml.cs">
	    <DependentUpon>MediaListItemBoxView.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\MediaLists\MediaListItemView.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\MediaLists\MediaListPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\MediaLists\MediaListView.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\MediaLists\MoviesPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\MediaLists\TVShowsPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\StatusBar.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\VideoPlayer\VideoPlayerPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Views\VideoPlayer\VideoPlayerView.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <MauiAsset Update="Resources\Raw\AboutAssets.txt">
	    <LogicalName>%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
	  </MauiAsset>
	</ItemGroup>

	<ItemGroup>
	  <MauiAsset Update="Resources\Raw\loading.mp4">
	    <LogicalName>%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
	  </MauiAsset>
	</ItemGroup>

	<ItemGroup>
	  <MauiAsset Update="Resources\Raw\secrets.json">
	    <CopyToOutputDirectory></CopyToOutputDirectory>
	    <LogicalName>%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
	  </MauiAsset>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Views\Categorization\MediaItemCardPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Homepage\CategorySelection.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Homepage\HomePageView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Homepage\HorizontalMediaItemCollection.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MainPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ManagementPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Management\AdministrativeTasks\AdminTasksView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Management\SettingsView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Management\SourcesView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Management\Sources\SourceConfigurationBox.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Management\Sources\SourceFTPConfigurationBox.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Management\Sources\SourceHttpConfigurationBox.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Management\Sources\SourceSSHConfigurationBox.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MediaLists\Cards\MovieCardPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MediaLists\Cards\MovieSetupView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MediaLists\Cards\TVShowCardPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MediaLists\Cards\TVShowSetupView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MediaLists\ListItems\MediaListItemBoxView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MediaLists\ListItems\NewListItemView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MediaLists\MediaListItemView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MediaLists\MediaListPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MediaLists\MediaListView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MediaLists\MoviesPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MediaLists\TVShowsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\StatusBar.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\VideoPlayer\VideoPlayerPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\VideoPlayer\VideoPlayerView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

</Project>
