// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoWebPlayer.Data;

#nullable disable

namespace VideoWebPlayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250812173712_UpdateMediaModels5")]
    partial class UpdateMediaModels5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MovieMediaItem", b =>
                {
                    b.Property<long>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MovieId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId", "MediaItemId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("MovieId1");

                    b.ToTable("MovieMediaItems");
                });

            modelBuilder.Entity("Setup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Setups");
                });

            modelBuilder.Entity("TVShowEpisodeMediaItem", b =>
                {
                    b.Property<long>("TVShowEpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TVShowEpisodeId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("TVShowEpisodeId", "MediaItemId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("TVShowEpisodeId1");

                    b.ToTable("TVShowEpisodeMediaItems");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sources")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MediaCollection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Changed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClassifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("MediaSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentMediaCollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaSourceId");

                    b.HasIndex("ParentMediaCollectionId");

                    b.ToTable("MediaCollections");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MediaItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Changed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClassifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("MediaCollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("TVShowEpisodeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaCollectionId");

                    b.HasIndex("MovieId");

                    b.HasIndex("TVShowEpisodeId");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MediaSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Changed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClassifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MediaSources");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.Movie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BannerPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Changed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClassifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Credits")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<long>("MediaSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MovieCollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plot")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PosterPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PremieredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Studios")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BannerPictureId");

                    b.HasIndex("MovieCollectionId");

                    b.HasIndex("PosterPictureId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MovieCollection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BannerPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Changed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClassifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("MediaSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PosterPictureId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BannerPictureId");

                    b.HasIndex("PosterPictureId");

                    b.ToTable("MovieCollections");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.Picture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.TVShow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BannerPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Changed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClassifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<long>("MediaSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plot")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PosterPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Premiered")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Studio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BannerPictureId");

                    b.HasIndex("PosterPictureId");

                    b.ToTable("TVShows");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.TVShowEpisode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BannerPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Changed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClassifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("MediaSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plot")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PosterPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PremieredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("TVShowSeasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BannerPictureId");

                    b.HasIndex("PosterPictureId");

                    b.HasIndex("TVShowSeasonId");

                    b.ToTable("TVShowEpisodes");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.TVShowSeason", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BannerPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Changed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClassifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("MediaSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PosterPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TVShowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BannerPictureId");

                    b.HasIndex("PosterPictureId");

                    b.HasIndex("TVShowId");

                    b.ToTable("TVShowSeasons");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoWebPlayer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieMediaItem", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoWebPlayer.Data.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoWebPlayer.Data.Movie", null)
                        .WithMany("MovieMediaItems")
                        .HasForeignKey("MovieId1");

                    b.Navigation("MediaItem");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("TVShowEpisodeMediaItem", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoWebPlayer.Data.TVShowEpisode", "TVShowEpisode")
                        .WithMany()
                        .HasForeignKey("TVShowEpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoWebPlayer.Data.TVShowEpisode", null)
                        .WithMany("TVShowEpisodeMediaItems")
                        .HasForeignKey("TVShowEpisodeId1");

                    b.Navigation("MediaItem");

                    b.Navigation("TVShowEpisode");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MediaCollection", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.MediaSource", "MediaSource")
                        .WithMany("MediaCollections")
                        .HasForeignKey("MediaSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoWebPlayer.Data.MediaCollection", "ParentMediaCollection")
                        .WithMany("ChildCollections")
                        .HasForeignKey("ParentMediaCollectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MediaSource");

                    b.Navigation("ParentMediaCollection");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MediaItem", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.MediaCollection", "MediaCollection")
                        .WithMany("MediaItems")
                        .HasForeignKey("MediaCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoWebPlayer.Data.Movie", null)
                        .WithMany("MediaItems")
                        .HasForeignKey("MovieId");

                    b.HasOne("VideoWebPlayer.Data.TVShowEpisode", null)
                        .WithMany("MediaItems")
                        .HasForeignKey("TVShowEpisodeId");

                    b.Navigation("MediaCollection");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.Movie", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.Picture", "BannerPicture")
                        .WithMany()
                        .HasForeignKey("BannerPictureId");

                    b.HasOne("VideoWebPlayer.Data.MovieCollection", "MovieCollection")
                        .WithMany("Movies")
                        .HasForeignKey("MovieCollectionId");

                    b.HasOne("VideoWebPlayer.Data.Picture", "PosterPicture")
                        .WithMany()
                        .HasForeignKey("PosterPictureId");

                    b.Navigation("BannerPicture");

                    b.Navigation("MovieCollection");

                    b.Navigation("PosterPicture");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MovieCollection", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.Picture", "BannerPicture")
                        .WithMany()
                        .HasForeignKey("BannerPictureId");

                    b.HasOne("VideoWebPlayer.Data.Picture", "PosterPicture")
                        .WithMany()
                        .HasForeignKey("PosterPictureId");

                    b.Navigation("BannerPicture");

                    b.Navigation("PosterPicture");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.Picture", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.TVShow", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.Picture", "BannerPicture")
                        .WithMany()
                        .HasForeignKey("BannerPictureId");

                    b.HasOne("VideoWebPlayer.Data.Picture", "PosterPicture")
                        .WithMany()
                        .HasForeignKey("PosterPictureId");

                    b.Navigation("BannerPicture");

                    b.Navigation("PosterPicture");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.TVShowEpisode", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.Picture", "BannerPicture")
                        .WithMany()
                        .HasForeignKey("BannerPictureId");

                    b.HasOne("VideoWebPlayer.Data.Picture", "PosterPicture")
                        .WithMany()
                        .HasForeignKey("PosterPictureId");

                    b.HasOne("VideoWebPlayer.Data.TVShowSeason", "TVShowSeason")
                        .WithMany("Episodes")
                        .HasForeignKey("TVShowSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BannerPicture");

                    b.Navigation("PosterPicture");

                    b.Navigation("TVShowSeason");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.TVShowSeason", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.Picture", "BannerPicture")
                        .WithMany()
                        .HasForeignKey("BannerPictureId");

                    b.HasOne("VideoWebPlayer.Data.Picture", "PosterPicture")
                        .WithMany()
                        .HasForeignKey("PosterPictureId");

                    b.HasOne("VideoWebPlayer.Data.TVShow", "TVShow")
                        .WithMany("Seasons")
                        .HasForeignKey("TVShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BannerPicture");

                    b.Navigation("PosterPicture");

                    b.Navigation("TVShow");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MediaCollection", b =>
                {
                    b.Navigation("ChildCollections");

                    b.Navigation("MediaItems");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MediaSource", b =>
                {
                    b.Navigation("MediaCollections");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.Movie", b =>
                {
                    b.Navigation("MediaItems");

                    b.Navigation("MovieMediaItems");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MovieCollection", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.TVShow", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.TVShowEpisode", b =>
                {
                    b.Navigation("MediaItems");

                    b.Navigation("TVShowEpisodeMediaItems");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.TVShowSeason", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
