// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoWebPlayer.Data;

#nullable disable

namespace VideoWebPlayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260822103156_AddContinueWatchingListOrder")]
    partial class AddContinueWatchingListOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("GenreName", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("GenreNames");
                });

            modelBuilder.Entity("MediaSourceUser", b =>
                {
                    b.Property<long>("MediaSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("MediaSourceId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("MediaSourceUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MovieGenre", b =>
                {
                    b.Property<long>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenres");
                });

            modelBuilder.Entity("MovieMediaItem", b =>
                {
                    b.Property<long>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MovieId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId", "MediaItemId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("MovieId1");

                    b.ToTable("MovieMediaItems");
                });

            modelBuilder.Entity("RecentEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("MediaSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MovieCollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TVShowEpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TVShowId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TVShowSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RecentEntries");
                });

            modelBuilder.Entity("Setup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DataVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GenresChanged")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaCollectionScanIntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScanProcessIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Setups");
                });

            modelBuilder.Entity("TVShowEpisodeMediaItem", b =>
                {
                    b.Property<long>("TVShowEpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TVShowEpisodeId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("TVShowEpisodeId", "MediaItemId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("TVShowEpisodeId1");

                    b.ToTable("TVShowEpisodeMediaItems");
                });

            modelBuilder.Entity("TVShowGenre", b =>
                {
                    b.Property<long>("TVShowId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TVShowId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("TVShowGenres");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sources")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("VideoWebPlayer.Data.BackupOperationHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Generation")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BackupOperationHistories");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.BackupSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutomaticBackupsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FatherRetentionCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrandfatherRetentionCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MaxUploadSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SonRetentionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BackupSettings");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.BlockedLoginIp", b =>
                {
                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BlockedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Failures")
                        .HasColumnType("INTEGER");

                    b.HasKey("Ip");

                    b.HasIndex("BlockedAtUtc");

                    b.ToTable("BlockedLoginIps");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.ContinueWatchingEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<long>("ListOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Position")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TVShowEpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("TVShowEpisodeId");

                    b.HasIndex("UserId", "MovieId");

                    b.HasIndex("UserId", "TVShowEpisodeId");

                    b.HasIndex("UserId", "ListOrder", "UpdatedAt");

                    b.ToTable("ContinueWatchingEntries");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.FavoriteEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("MovieCollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TVShowEpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TVShowId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TVShowSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FavoriteEntries");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.Genre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaSourceId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MediaCollection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Changed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClassifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Classifyable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("MediaSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentMediaCollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScanDueAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Skip")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaSourceId");

                    b.HasIndex("ParentMediaCollectionId");

                    b.ToTable("MediaCollections");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MediaItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Changed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClassifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("MediaCollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("TVShowEpisodeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaCollectionId");

                    b.HasIndex("MovieId");

                    b.HasIndex("TVShowEpisodeId");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MediaSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Changed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClassifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("IconPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IconPictureId");

                    b.ToTable("MediaSources");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MediaSourceIcon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("MediaSourceIcons");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.Movie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BannerPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Changed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClassifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Credits")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FanartPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenreNames")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsManuallyEdited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<long>("MediaSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MovieCollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plot")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PosterPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PremieredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Studios")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BannerPictureId");

                    b.HasIndex("FanartPictureId");

                    b.HasIndex("MovieCollectionId");

                    b.HasIndex("PosterPictureId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MovieCollection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BannerPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Changed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClassifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FanartPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManuallyEdited")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PosterPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PremieredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BannerPictureId");

                    b.HasIndex("FanartPictureId");

                    b.HasIndex("PosterPictureId");

                    b.ToTable("MovieCollections");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.Picture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGeneratedBackground")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("EpisodeId", "IsGeneratedBackground");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.TVShow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BannerPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Changed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClassifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FanartPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenreNames")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsManuallyEdited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<long>("MediaSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plot")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PosterPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PremieredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Studio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BannerPictureId");

                    b.HasIndex("FanartPictureId");

                    b.HasIndex("PosterPictureId");

                    b.ToTable("TVShows");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.TVShowEpisode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BackgroundImageGeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("BackgroundImageRequiresUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BannerPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Changed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClassifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FanartPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("GeneratedBackgroundPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManuallyEdited")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plot")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PosterPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PremieredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("TVShowSeasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BannerPictureId");

                    b.HasIndex("FanartPictureId");

                    b.HasIndex("GeneratedBackgroundPictureId");

                    b.HasIndex("PosterPictureId");

                    b.HasIndex("TVShowSeasonId");

                    b.ToTable("TVShowEpisodes");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.TVShowSeason", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BannerPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Changed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClassifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FanartPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManuallyEdited")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PosterPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PremieredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("TVShowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BannerPictureId");

                    b.HasIndex("FanartPictureId");

                    b.HasIndex("PosterPictureId");

                    b.HasIndex("TVShowId");

                    b.ToTable("TVShowSeasons");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.UpdateSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowPrereleaseUpdates")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutomaticChecksEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutomaticDownloadEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutomaticInstallationEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CancelInstallationOnBackupFailure")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheckIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CreateBackupBeforeInstallation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetainedUpdateBackupCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateBackupPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UpdateSettings");
                });

            modelBuilder.Entity("GenreName", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.Genre", "Genre")
                        .WithMany("AlternateNames")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MediaSourceUser", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.MediaSource", "MediaSource")
                        .WithMany("MediaSourceUsers")
                        .HasForeignKey("MediaSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoWebPlayer.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaSource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoWebPlayer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieGenre", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoWebPlayer.Data.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieMediaItem", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoWebPlayer.Data.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoWebPlayer.Data.Movie", null)
                        .WithMany("MovieMediaItems")
                        .HasForeignKey("MovieId1");

                    b.Navigation("MediaItem");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("TVShowEpisodeMediaItem", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoWebPlayer.Data.TVShowEpisode", "TVShowEpisode")
                        .WithMany()
                        .HasForeignKey("TVShowEpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoWebPlayer.Data.TVShowEpisode", null)
                        .WithMany("TVShowEpisodeMediaItems")
                        .HasForeignKey("TVShowEpisodeId1");

                    b.Navigation("MediaItem");

                    b.Navigation("TVShowEpisode");
                });

            modelBuilder.Entity("TVShowGenre", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.Genre", "Genre")
                        .WithMany("TVShowGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoWebPlayer.Data.TVShow", "TVShow")
                        .WithMany("TVShowGenres")
                        .HasForeignKey("TVShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("TVShow");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.ContinueWatchingEntry", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VideoWebPlayer.Data.TVShowEpisode", "TVShowEpisode")
                        .WithMany()
                        .HasForeignKey("TVShowEpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Movie");

                    b.Navigation("TVShowEpisode");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.Genre", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.MediaSource", "MediaSource")
                        .WithMany()
                        .HasForeignKey("MediaSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaSource");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MediaCollection", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.MediaSource", "MediaSource")
                        .WithMany("MediaCollections")
                        .HasForeignKey("MediaSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoWebPlayer.Data.MediaCollection", "ParentMediaCollection")
                        .WithMany("ChildCollections")
                        .HasForeignKey("ParentMediaCollectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MediaSource");

                    b.Navigation("ParentMediaCollection");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MediaItem", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.MediaCollection", "MediaCollection")
                        .WithMany("MediaItems")
                        .HasForeignKey("MediaCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoWebPlayer.Data.Movie", null)
                        .WithMany("MediaItems")
                        .HasForeignKey("MovieId");

                    b.HasOne("VideoWebPlayer.Data.TVShowEpisode", null)
                        .WithMany("MediaItems")
                        .HasForeignKey("TVShowEpisodeId");

                    b.Navigation("MediaCollection");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MediaSource", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.MediaSourceIcon", "IconPicture")
                        .WithMany()
                        .HasForeignKey("IconPictureId");

                    b.Navigation("IconPicture");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.Movie", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.Picture", "BannerPicture")
                        .WithMany()
                        .HasForeignKey("BannerPictureId");

                    b.HasOne("VideoWebPlayer.Data.Picture", "FanartPicture")
                        .WithMany()
                        .HasForeignKey("FanartPictureId");

                    b.HasOne("VideoWebPlayer.Data.MovieCollection", "MovieCollection")
                        .WithMany("Movies")
                        .HasForeignKey("MovieCollectionId");

                    b.HasOne("VideoWebPlayer.Data.Picture", "PosterPicture")
                        .WithMany()
                        .HasForeignKey("PosterPictureId");

                    b.Navigation("BannerPicture");

                    b.Navigation("FanartPicture");

                    b.Navigation("MovieCollection");

                    b.Navigation("PosterPicture");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MovieCollection", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.Picture", "BannerPicture")
                        .WithMany()
                        .HasForeignKey("BannerPictureId");

                    b.HasOne("VideoWebPlayer.Data.Picture", "FanartPicture")
                        .WithMany()
                        .HasForeignKey("FanartPictureId");

                    b.HasOne("VideoWebPlayer.Data.Picture", "PosterPicture")
                        .WithMany()
                        .HasForeignKey("PosterPictureId");

                    b.Navigation("BannerPicture");

                    b.Navigation("FanartPicture");

                    b.Navigation("PosterPicture");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.Picture", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.TVShow", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.Picture", "BannerPicture")
                        .WithMany()
                        .HasForeignKey("BannerPictureId");

                    b.HasOne("VideoWebPlayer.Data.Picture", "FanartPicture")
                        .WithMany()
                        .HasForeignKey("FanartPictureId");

                    b.HasOne("VideoWebPlayer.Data.Picture", "PosterPicture")
                        .WithMany()
                        .HasForeignKey("PosterPictureId");

                    b.Navigation("BannerPicture");

                    b.Navigation("FanartPicture");

                    b.Navigation("PosterPicture");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.TVShowEpisode", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.Picture", "BannerPicture")
                        .WithMany()
                        .HasForeignKey("BannerPictureId");

                    b.HasOne("VideoWebPlayer.Data.Picture", "FanartPicture")
                        .WithMany()
                        .HasForeignKey("FanartPictureId");

                    b.HasOne("VideoWebPlayer.Data.Picture", "GeneratedBackgroundPicture")
                        .WithMany()
                        .HasForeignKey("GeneratedBackgroundPictureId");

                    b.HasOne("VideoWebPlayer.Data.Picture", "PosterPicture")
                        .WithMany()
                        .HasForeignKey("PosterPictureId");

                    b.HasOne("VideoWebPlayer.Data.TVShowSeason", "TVShowSeason")
                        .WithMany("Episodes")
                        .HasForeignKey("TVShowSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BannerPicture");

                    b.Navigation("FanartPicture");

                    b.Navigation("GeneratedBackgroundPicture");

                    b.Navigation("PosterPicture");

                    b.Navigation("TVShowSeason");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.TVShowSeason", b =>
                {
                    b.HasOne("VideoWebPlayer.Data.Picture", "BannerPicture")
                        .WithMany()
                        .HasForeignKey("BannerPictureId");

                    b.HasOne("VideoWebPlayer.Data.Picture", "FanartPicture")
                        .WithMany()
                        .HasForeignKey("FanartPictureId");

                    b.HasOne("VideoWebPlayer.Data.Picture", "PosterPicture")
                        .WithMany()
                        .HasForeignKey("PosterPictureId");

                    b.HasOne("VideoWebPlayer.Data.TVShow", "TVShow")
                        .WithMany("Seasons")
                        .HasForeignKey("TVShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BannerPicture");

                    b.Navigation("FanartPicture");

                    b.Navigation("PosterPicture");

                    b.Navigation("TVShow");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.Genre", b =>
                {
                    b.Navigation("AlternateNames");

                    b.Navigation("MovieGenres");

                    b.Navigation("TVShowGenres");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MediaCollection", b =>
                {
                    b.Navigation("ChildCollections");

                    b.Navigation("MediaItems");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MediaSource", b =>
                {
                    b.Navigation("MediaCollections");

                    b.Navigation("MediaSourceUsers");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.Movie", b =>
                {
                    b.Navigation("MediaItems");

                    b.Navigation("MovieGenres");

                    b.Navigation("MovieMediaItems");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.MovieCollection", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.TVShow", b =>
                {
                    b.Navigation("Seasons");

                    b.Navigation("TVShowGenres");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.TVShowEpisode", b =>
                {
                    b.Navigation("MediaItems");

                    b.Navigation("TVShowEpisodeMediaItems");
                });

            modelBuilder.Entity("VideoWebPlayer.Data.TVShowSeason", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
